estimator_adapter:
  ros__parameters:
    input_topic: /ov_msckf/odomimu
    output_topic: /mavros/odometry/out
    output_enabled: false
    replay_mode: true
    send_velocity: false
    output_rate_hz: 30.0
    max_input_age_seconds: 0.20
    frame_id: odom
    child_frame_id: base_link
